
---


- name: Cisco Wired Campus Design
  hosts: gns3-ios
  gather_facts: false
  connection: local
  vars:
    cli:
      username: david
      password: cisco
      transport: cli
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: CONFIGURE IOS SYSLOG SERVER
    ios_config:
      lines:
        - logging host 192.168.10.12
        - logging host 10.10.10.10
    register: print_output
  -  debug: var=print_output
